### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by hfiguiere** [flathub/me.aandrew.ytdownloader#5]
This packag dropped aarch64 support. Not nice.

**Comment by aandrew-me** [comment]
I would love to have support for aarch64. However in the build file I download a binary for x64 arch. Is there any way to specify a different binary download url for aarch64 in the build file?

**Comment by hfiguiere** [comment]
why don't you build from source? **many** packages build ffmpeg.

**Comment by aandrew-me** [comment]
The ffmpeg I am using is a different version and I don't know and couldn't find how to build it.

**Comment by hfiguiere** [comment]
a lot of packages build ffmpeg. it's easy to find.

**Comment by aandrew-me** [comment]
Okay I will see what I can do thanks
